### PR TITLE
Patch-set for v5.19

### PR DESCRIPTION
**Pull request by dnlplm**

### CODE REVIEW

**Comment by dnlplm** [comment]
@telit-fabiopo, please check

**Comment by telit-fabiopo** [comment]
IMHO you should cherry-pick the two upstream patches:
0c60d1657d3d (net: wwan: mhi_wwan_ctrl: Add DUN2 to have a secondary AT port, 2022-09-16)
479aa3b0ec2e (bus: mhi: host: pci_generic: Add a secondary AT port to Telit FN990, 2022-09-16)

Also i think you should put the "wwam: add NMEA type" before the patch for FN980 v2 in order to be available before it's used.

**Comment by dnlplm** [comment]
> IMHO you should cherry-pick the two upstream patches:
0c60d1657d3d (net: wwan: mhi_wwan_ctrl: Add DUN2 to have a secondary AT port, 2022-09-16)
479aa3b0ec2e (bus: mhi: host: pci_generic: Add a secondary AT port to Telit FN990, 2022-09-16)
>
> Also i think you should put the "wwam: add NMEA type" before the patch for FN980 v2 in order to be available before it's used.

Ack, I'll rework the PR.

**Comment by telit-fabiopo** [comment]
IMHO it will be cool if backported commits from upstream will be cherry-pick with "git cherry-pick -x <sha>" in order to tracks the origin.
e.g.
0001-bus-mhi-host-Move-IRQ-allocation-to-controller-regis.patch -> 1227d2a20cd7319fb45c62fab4b252600e0308bf
0002-bus-mhi-host-Fix-up-null-pointer-access-in-mhi_irq_h.patch -> ffb384c269dce238c588e0e8e3a85c0ec098a904
0009-net-wwan-mhi_wwan_ctrl-Add-DUN2-to-have-a-secondary-.patch -> 0c60d1657d3d 
0012-bus-mhi-host-pci_generic-Add-a-secondary-AT-port-to-.patch -> 479aa3b0ec2e 

Also to avoid unneccessary conflicts  I suggest to move all those patches at the beginning.

Thanks

**Comment by telit-fabiopo** [comment]
Ok for me.

**Comment by dnlplm** [comment]
Added commit to rework the firmware upgrade procedure.

**Pull request merged**
